tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"

brew "gh"
brew "git"
brew "gnutls"
brew "gnupg"
brew "jq"
brew "node@22"
brew "pinentry-mac"

cask "1password"
cask "bettertouchtool"
cask "docker"
cask "google-chrome"
cask "google-chrome@canary"
cask "karabiner-elements"
cask "loopback"
cask "microsoft-edge"
cask "microsoft-teams"
cask "pika"
cask "viscosity"
cask "visual-studio-code"
cask "vmware-fusion"
cask "zoom"

