tap "homebrew/cask"
tap "homebrew/cask-versions"

brew "diff-so-fancy"
brew "gh"
brew "git"
brew "gnupg"
brew "mas"
brew "node@14"
brew "pinentry-mac"
brew "shellcheck"

cask "bettertouchtool"
cask "encryptme"
cask "figma"
cask "google-chrome"
cask "hazel"
cask "muzzle"
cask "nova"
cask "paw"
cask "sketch"
cask "visual-studio-code"
cask "zoom"