tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"

brew "gh"
brew "git"
brew "gnutls"
brew "gnupg"
brew "jq"
brew "ruby"
brew "node@22"
brew "pinentry-mac"

cask "1password"
cask "bettertouchtool"
cask "google-chrome"
cask "microsoft-teams"
cask "visual-studio-code@insiders"
cask "vmware-fusion"
cask "zoom"
