#!/usr/bin/env zsh
# shellcheck shell=bash

# shellcheck disable=SC2012
VERSION="$(ls -t /vscode/bin/linux-x64 | head -n1)"
PATH="/vscode/bin/linux-x64/${VERSION}/bin/remote-cli:${PATH}"
VSCODE_IPC_HOOK_CLI=$(echo /tmp/vscode-ipc-*.sock)

rm -Rf /root/.vscode-remote/extensions/*
code --list-extensions | xargs -I@ code --uninstall-extension @
cat << EOB | xargs -I@ code --install-extension @
  "bierner.jsdoc-markdown-highlighting"
  "castwide.solargraph"
  "dbaeumer.vscode-eslint"
  "EditorConfig.EditorConfig"
  "esbenp.prettier-vscode"
  "GitHub.codespaces"
  "kaiwood.endwise"
  "manuelpuyol.erb-linter"
  "mikestead.dotenv"
  "rebornix.ruby"
  "redhat.vscode-yaml"
  "soutaro.rbs-syntax"
  "soutaro.steep-vscode"
  "stylelint.vscode-stylelint"
  "timonwong.shellcheck"
  "VisualStudioExptTeam.vscodeintellicode"
  "wingrunr21.vscode-ruby"
EOB