#!/usr/bin/env zsh
# shellcheck shell=bash
setopt pipefail

# Configure `apt`
sudo tee /etc/apt/apt.conf.d/90assumeyes << EOF
APT::Get::Assume-Yes "true";
EOF

# Add Git repository
if [[ $(cat /etc/debian_version 2>/dev/null) == *"10."* ]] && [ ! -f /etc/apt/sources.list.d/git-core.list ]; then
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
    echo "deb http://ppa.launchpad.net/git-core/ppa/ubuntu eoan main" | sudo tee /etc/apt/sources.list.d/git-core.list
fi

# Update package lists
sudo apt update
sudo apt full-upgrade
sudo apt autoremove