#!/usr/bin/env zsh
# shellcheck shell=bash

# shellcheck disable=SC2012
PATH="/vscode/bin/linux-x64/$(ls -t /vscode/bin/linux-x64 | head -n1)/bin/remote-cli:${PATH}"

# Workaround for "Command is only available in WSL or inside a Visual Studio Code terminal."
# shellcheck disable=SC2010
VSCODE_IPC_HOOK_CLI="/tmp/$(ls -t /tmp | grep vscode-ipc | head -n1)"
export VSCODE_IPC_HOOK_CLI

rm -Rf /root/.vscode-remote/extensions/*
code --list-extensions | xargs -I@ code --uninstall-extension @
cat << EOB | xargs -I@ code --install-extension @
  "bierner.jsdoc-markdown-highlighting"
  "castwide.solargraph"
  "dbaeumer.vscode-eslint"
  "EditorConfig.EditorConfig"
  "esbenp.prettier-vscode"
  "GitHub.codespaces"
  "kaiwood.endwise"
  "manuelpuyol.erb-linter"
  "mikestead.dotenv"
  "rebornix.ruby"
  "redhat.vscode-yaml"
  "soutaro.rbs-syntax"
  "soutaro.steep-vscode"
  "stylelint.vscode-stylelint"
  "timonwong.shellcheck"
  "VisualStudioExptTeam.vscodeintellicode"
  "wingrunr21.vscode-ruby"
EOB