#!/usr/bin/env zsh

yarn() {
  # Upgrade all packages to the latest available versions,
  # and update version numbers in 'package.json' and 'package-lock.json'.
  if [[ "$1" == "global" ]] && [[ "$2" == "list" ]]
  then
    node -pe 'Object.entries(JSON.parse(process.argv[1]).dependencies).map(x=>x.join("@"))' "$(cat $(command yarn global dir)/package.json)"
    return $?
  fi

  command "yarn" "$@"
  return $?
}
