#!/usr/bin/env zsh

yarn() {
  # List all global packages, even those without binaries
  # Workaround for https://github.com/yarnpkg/yarn/issues/5725
  if [[ "$1" == "global" ]] && [[ "$2" == "list" ]]
  then
    node -pe 'Object.entries(JSON.parse(process.argv[1]).dependencies).map(x=>x.join("@"))' "$(cat $(command yarn global dir)/package.json)"
    return $?
  fi

  command "yarn" "$@"
  return $?
}
