#!/usr/bin/env bash

git() {
  command=$1
  shift 1
  case $command in

  # Create a new branch with the same name if one does not exist,
  # safer than `git config --global push.default current`.
  "push")
    BRANCH_NAME=$(command git rev-parse --abbrev-ref HEAD)
    if [[ -z $(command git config "branch.$BRANCH_NAME.merge") && -z "$@" ]]; then
      command git push --set-upstream origin "$BRANCH_NAME"
    elif [[ -z $(command git config "branch.$BRANCH_NAME.merge") ]]; then
      command git push --set-upstream "$@"
    else
      command git push "$@"
    fi
  ;;

  "diff")
    command git diff --color "$@" | diff-so-fancy
  ;;

  *)
    command git "${command}" "$@"
  ;;
  
  esac
  return $?
}
